### ISSUE TITLE
Installation permissions:  

### ISSUE THREAD

**Issue by rafael5** [georgzurbonsen/Beyond4P_Distribution#4]
Enter the license key (or [Enter] to skip): 1C 93 A5 BB  EF 88 F8 89  DF BB C1 E8  94 87 22 62  52 A1 BB D9
    Enter the corresponding license holder name: rafael
    The length of the license key is not correct.  Please retry.

    Enter the license key (or [Enter] to skip):

**Comment by georgzurbonsen** [comment]
Von: Rafael Richards <notifications@github.com> 
Gesendet: Sonntag, 2. Februar 2020 22:40
An: georgzurbonsen/Beyond4P_Distribution <Beyond4P_Distribution@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [georgzurbonsen/Beyond4P_Distribution] Installation permissions: (#4)

 

Enter the license key (or [Enter] to skip): 1C 93 A5 BB  EF 88 F8 89  DF BB C1 E8  94 87 22 62  52 A1 BB D9
Enter the corresponding license holder name: rafael
The length of the license key is not correct.  Please retry.
 
Enter the license key (or [Enter] to skip):
